version: '3.8'

services:
  # NestJS Application (Development)
  api:
    container_name: visualify-ai-api
    build:
      context: ../../
      dockerfile: ./docker/dev/Dockerfile
    volumes:
      - ../../:/usr/src/app
      - /usr/src/app/node_modules
      - ../../uploads:/usr/src/app/uploads
    ports:
      - "${PORT:-4300}:4300"
      - "9229:9229" # Port for debugger
    env_file:
      - ../../.env
    environment:
      # Override các host để sử dụng Docker service names
      - NODE_ENV=development
      - DB_HOST=postgres
      - REDIS_HOST=redis
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - visualify-ai-network-dev
    # Enables debugging
    command: npm run start:debug

  # PostgreSQL Database
  postgres:
    container_name: visualify-ai-postgres
    image: postgres:16-alpine
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      # - ../../docker/dev/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"
    env_file:
      - ../../.env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD:-122333aA@}
      - POSTGRES_USER=${DB_USERNAME:-postgres}
      - POSTGRES_DB=${DB_DATABASE:-visualify-ai-database}
    networks:
      - visualify-ai-network-dev
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-postgres} -d ${DB_DATABASE:-visualify-ai-database}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Redis
  redis:
    container_name: visualify-ai-redis
    image: redis:7-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD:-122333aA@}
    ports:
      - "6379:6379"
    volumes:
      - redis_data_dev:/data
    networks:
      - visualify-ai-network-dev
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5


volumes:
  postgres_data_dev:
  redis_data_dev:

networks:
  visualify-ai-network-dev:
    driver: bridge